CPSX/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from my_app import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home, name='home'),
    #url(r'^about$', views.about, name='about'),
    #url(r'^compete$', views.compete, name='compete'),
    #url(r'^competitions$', views.competitions, name='competitions'),
    url(r'^guest$',views.guest,name='guest'),
    url(r'^loggedIn$',views.loggedIn,name='loggedIn'),
    url(r'^login', 'django.contrib.auth.views.login',name='login'),
    url(r'^register$', views.register,name='register'),
    #url(r'^accounts/',include('django.contrib.auth.urls')),
    #url(r'^',include('django.contrib.auth.urls')) # hashed out because using this logout logs the admin out
    url(r'^logout$', views.logout_view, name = 'loggedOut'),
    url(r'^contact/$', views.contact, name='contact'), # form to invite friends to participate
]

my_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Participant(models.Model):
    user = models.OneToOneField(User)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name + " " + self.user.username + " " + self.user.email


class Room(models.Model):
    room = models.TextField()
    key = models.TextField()
    test_taker = models.ForeignKey(Participant) # allows test_taker to inherit the participant attrinutes

    def __str__(self):
        return self.room + " " + self.key + self.test_taker.first_name + " " + self.test_taker.last_name + " " + \
               self.test_taker.username + " " + self.test_taker.email

my_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name','last_name','email')

class ContactForm(forms.Form):
    # the fields we want in the form
    subject = forms.CharField(max_length=100)
    contact_name = forms.CharField(required=True) # contact's name
    contact_email = forms.EmailField(required=True) # contact's email
    message = forms.CharField(required=True,widget=forms.Textarea) # message to invite friend
    cc_myself = forms.BooleanField(required=False)

my_app/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from my_app.models import Participant, Room
from django.views.decorators.csrf import csrf_exempt # fix later so thatcsrf exeemption isnt on loggedIn
from .forms import CustomUserCreationForm, ContactForm # allows the creation of individualized registration form
from django.contrib.auth import logout
import hashlib # to encode adn transform room number into a key
from my_app.forms import ContactForm # to create a user contact form



# Create your views here.
def home(request):
    # note: request is in the cycle. the request is you. whatever window you go to, you will be there.
    # request goes with everying
    # note: the context dictionary stores data that will be given to the html page, when it renders a page
    # html is always constructed by a python script
    context = dict()  # note: this dictionary stores datat that will be rendered on the html page
    return render(request, "home.html", context)
    # Q: what is render
    # note: tell it which page to render with
    # & html is always rendered after the data is retrieved from the html

def about(request):
    context = dict()
    return render(request,"about.html", context)

def compete(request):
    context = dict()
    return render(request,"compete.html", context)

def competitions(request):
    context = dict()
    return render(request,"competitions.html", context)

def guest(request):
    context = ()
    return render(request,"guest.html", context)

@csrf_exempt
def register(request):
    context = dict()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            rm_obj = Room(room = 'a', key='1')
            rm_obj.save()
            new_user = form.save()
            participant_obj = Participant(user = new_user,rm_1 = rm_obj)
            participant_obj.save()
            return HttpResponseRedirect("/login")
    else:
        form = CustomUserCreationForm()
    context['form'] = form
    return render(request, "registration/register.html", context)

def loggedIn(request):
    context = dict()
    the_user = request.user
    participant_obj = Participant.objects.get(user=the_user)
    rm_obj = Room(room = participant_obj.id , key= code(participant_obj.id))
    rm_obj.save()
    context['participant'] = participant_obj
    context['room'] = rm_obj
    return render(request,'loggedIn.html',context)

def code(a):
    mystring = str(a)
    hash_object = hashlib.md5(mystring.encode())
    return(hash_object.hexdigest())


def logout_view(request):
    logout(request)
    return render(request, "loggedOut.html")

# function to use for inviting friends to participate
def contact(request):
    form_class = ContactForm
    return render(request, 'contact.html')

'''def form.is_valid():
    subject = form.cleaned_data['subject']
    message = form.cleaned_data['message']
    sender = form.cleaned_data['sender']
    cc_myself = form.cleaned_data['cc_myself']
    recipients = ['info@example.com']
    if cc_myself:
        recipients.append(sender)
    send_mail(subject, message, sender, recipients)
    return HttpResponseRedirect('/thanks/')'''

'''# Q: what if this order was reversed & foreign key object switched.
            # therfore participant could be saved without a room
            # then, rather then having dummy room & key info, room & key could immediately be set equal to participant_obj.id'''

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invite Friend</title>
</head>
<body>


<h1>Contact</h1>

<form role="form" action="" method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <p><label for="id_subject">Subject:</label>
<input id="id_subject" type="text" name="subject" maxlength="100" /></p>

<p><label for="id_message">Message:</label>
<input type="text" name="message" id="id_message" /></p>

<p><label for="id_sender">Sender:</label>
<input type="email" name="sender" id="id_sender" /></p>

    <form role="form" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Submit</button>

<p><label for="id_cc_myself">Cc myself:</label>
<input type="checkbox" name="cc_myself" id="id_cc_myself" /></p>
    <button type="submit">Submit</button>

</form>


</body>
</html>

templates/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Here is some new information.
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CPSX</title>
    <style>
  h1 {
    font-family: Bitter;
    font-size: 400%; }
h2 {
    font-size: 100%;
    font-family: "Avenir Next";
    font-weight: bold;
}
#header {
    background-color: #57068c;
    color:white;
    text-align:center;
    padding:5px;}
}

        #left {
    line-height:30px;
    background-color:white;
    height:700px;
    width:100px;
    float:left;
    padding:5px;
}
           #right {
    line-height:30px;
    height:700px;
    width:100px;
    float:left;
    padding:5px;
}

#section {
    width:100px;
    float:left;
    padding:300px;}
        a:link    {color:darkorange; background-color:transparent; text-decoration:none}
    </style>
</head>

<body>
<div id="header">
    <center><h1> The Collaborative Learning Project!</h1><center></div>
<div id="left">
</div>

   <div id="right">

<p>
    <h2><a href = "about" >Learn More </a>
    <p>
    <a  href = "compete">Compete </a>
    <p>
    <a href="competitions">Competitions</a>
    <p>
 <p>
    <a href="guest">Guest</a>
       <p>
    Returning Users <a href = "loggedIn" >logged In</a>
    <p>
    New Users <a href = "register">register here</a>
    <p></h2>
       </div>
Returning users: <a href="login">Login here</a>
</p>
<p>
New users: <a href="register">Register here</a>
</body>
</html>

templates/loggedIn.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Hi {{ user }}. You've logged in!
Here is your room name: {{ room.room }}.
Here is your key: {{ room.key }}.
<h2>Your current balances:</h2><p>
<table style="width:30%">
<tr>
<th bgcolor=gray>Room Name</th>
<th bgcolor=gray>Room Key/th>
{% for room in investor.balances_set.all %}
<tr>
<td>{{balance.currency_id}}</td>
{% load humanize %}
{{ balance.value|floatformat:2|intcomma }}
</td>
</tr>
{% endfor %}
</table>
</center>
<a href = "logout" >Click here to logout</a>
</body>
</html>

templates/loggedOut.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout Success</title>
</head>
<body>
    You have been successfullylogged out!

<a href = "/ " >Click here to return to home page</a>
</body>
</html>